// This file contains an autogenerated list of files found in the ./res/block and ./res/texture/ directories

pub const TEXTURE_NAMES: [&'static str; 12] = ["bricks", "dirt", "glass", "grass_side", "grass_top", "pure_white", "quartz", "sand", "stone", "water", "wood", "wood_light"];
pub const BLOCK_NAMES: [&'static str; 11] = ["air.yaml", "brick.yaml", "dirt.yaml", "glass.yaml", "grass.yaml", "light.yaml", "quartz.yaml", "sand.yaml", "stone.yaml", "water.yaml", "wood.yaml"];
